[package]
name = "axum_macs"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
csv = "1.3.0"
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.39.2", features = ["full"] }
